/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.m06.fileutils;

public class FileUtlis {
    public boolean someLibraryMethod() {
        return true;
    }
}
