/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.m06.fileutils;
import java.io.File;
public class FileUtils {

    public static boolean isValidDirectory(String path) {
        File file = new File(path);
        File[] listfile = file.listFiles();
        if (!file.exists() || !file.isDirectory() || listfile.length > 0 || file.getAbsolutePath().contains(" ")) {
            return false;
        }

        return true;
    }

    public static void main(String[] args) {
        System.out.println(isValidDirectory("C:\\Users\\10034356\\source\\repos\\fileutils\\FileUtils\\lib\\src\\main\\resources"));
    }
}